export const GET_DATA_SUCCESS_2 = "GET_DATA_SUCCESS_2";
export const GET_TOPIC_SUCCESS_2 = "GET_TOPIC_SUCCESS_2";
export const GET_FOLLOWING_TOPIC_SUCCESS_2 = "GET_FOLLOWING_TOPIC_SUCCESS_2";
export const GET_PEOPLE_SUCCESS_2 = "GET_PEOPLE_SUCCESS_2";
export const GET_DATA_FAILURE_2 = "GET_DATA_FAILURE_2";
export const GET_DATA_REQUEST_2 = "GET_DATA_REQUEST_2";

export const POST_BLOG_REQUEST = "POST_BLOG_REQUEST";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const POST_BLOG_FAILURE = "POST_BLOG_FAILURE";

export const TOPIC_SUCCESS = "TOPIC_SUCCESS";
