export const GET_DATA_SUCCESS_2 = "GET_DATA_SUCCESS_2";
export const GET_TOPIC_SUCCESS_2 = "GET_TOPIC_SUCCESS_2";
export const GET_FOLLOWING_TOPIC_SUCCESS_2 = "GET_FOLLOWING_TOPIC_SUCCESS_2";
export const GET_PEOPLE_SUCCESS_2 = "GET_PEOPLE_SUCCESS_2";
export const GET_DATA_FAILURE_2 = "GET_DATA_FAILURE_2";
export const GET_DATA_REQUEST_2 = "GET_DATA_REQUEST_2";
