export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_TOPIC_SUCCESS = "GET_TOPIC_SUCCESS";
export const GET_TRENDING_SUCCESS = "GET_TRENDING_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const GET_DATA_REQUEST = "GET_DATA_REQUEST";

export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE";

export const GET_SINGLE_BLOG = "GET_SINGLE_BLOG";
